{
 "title": "Data Processing Monitoring",
 "tags": [
  "Bigdata",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Data Processing Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard demonstrates 6 different charts in a single dashboard that provides a single view for the data processing pipeline [metrics](https://cloud.google.com/monitoring/api/metrics_gcp). Read the blog post [Use SRE principles to monitor pipelines with Cloud Monitoring dashboards](https://cloud.google.com/blog/products/management-tools/the-right-metrics-to-monitor-cloud-data-pipelines) for additional details."
   }
  },
  {
   "title": "Dataflow (traffic)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "dataflow_job"
      ],
      "groupBys": [ "resource.label.job_name" ],
      "metricKind": "DELTA",
      "metricType": "dataflow.googleapis.com/job/elements_produced_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Pubsub (traffic)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "pubsub_topic"
      ],
      "groupBys": [ "metric.label.response_code" ],
      "metricKind": "DELTA",
      "metricType": "pubsub.googleapis.com/topic/send_request_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "BigQuery (traffic)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "bigquery_dataset"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "bigquery.googleapis.com/storage/uploaded_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "System lag (latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "dataflow_job"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "dataflow.googleapis.com/job/system_lag",
      "projectName": "$project",
      "unit": "s",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "dataflow_job"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "dataflow.googleapis.com/job/data_watermark_age",
      "projectName": "$project",
      "unit": "s",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Dataflow processing volume (throughput)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "dataflow_job"
      ],
      "groupBys": [ "resource.label.job_name" ],
      "metricKind": "GAUGE",
      "metricType": "dataflow.googleapis.com/job/element_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Pipeline logging (errors)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "bigquery_dataset",
       "AND",
       "metric.label.severity",
       "=",
       "ERROR"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "logging.googleapis.com/log_entry_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "pubsub_topic",
       "AND",
       "metric.label.severity",
       "=",
       "ERROR"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "logging.googleapis.com/log_entry_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "dataflow_job",
       "AND",
       "metric.label.severity",
       "=",
       "ERROR"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "logging.googleapis.com/log_entry_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}